# Generated by Django 5.2.6 on 2025-09-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, default="", max_length=10, unique=True),
        ),
    ]
