# Generated by Django 5.2.6 on 2025-09-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="size",
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="상세주소"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("Female", "여성"), ("Male", "남성")],
                default="F",
                max_length=10,
                verbose_name="성별",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="이메일"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                blank=True, default="", max_length=10, unique=True, verbose_name="닉네임"
            ),
        ),
        migrations.AlterField(
            model_name="userbio",
            name="ball_foot",
            field=models.CharField(
                choices=[("Narrow", "좁음"), ("Regular", "보통"), ("Wide", "넓음")],
                default="R",
                max_length=10,
                verbose_name="발볼 크기",
            ),
        ),
        migrations.AlterField(
            model_name="userbio",
            name="favorite_brand",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="선호 브랜드"
            ),
        ),
    ]
