# Generated by Django 5.2.6 on 2025-09-21 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExampleBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ExampleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ExampleProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                ("image_url", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("source_url", models.TextField()),
                ("weight", models.IntegerField(blank=True, null=True)),
                ("stock", models.IntegerField(default=0)),
                ("rating", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mall.examplebrand",
                    ),
                ),
                ("categories", models.ManyToManyField(to="mall.examplecategory")),
            ],
        ),
    ]
