# Generated by Django 5.2.6 on 2025-09-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mall", "0002_examplebrand_examplecategory_exampleproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exampleproduct",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
