# Generated by Django 5.2.6 on 2025-09-26 07:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WishList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "shoe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.shoe"
                    ),
                ),
            ],
        ),
    ]
