# Generated by Django 5.2.6 on 2025-09-23 10:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mypage", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WishList",
        ),
    ]
