# Generated by Django 5.2.6 on 2025-09-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("brand_img", models.ImageField(blank=True, upload_to="brand/")),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=10)),
                ("quantity", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Marathon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=200)),
                ("distance", models.CharField(max_length=50)),
                ("price", models.IntegerField(default=0)),
                ("website_url", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_price", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=20)),
                ("addr_num", models.TextField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("detail_address", models.TextField()),
                ("order_message", models.TextField(blank=True, default="")),
                ("pay_method", models.IntegerField(default=0)),
                ("status", models.CharField(default="주문완료", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=10)),
                ("quantity", models.IntegerField(default=0)),
                ("price", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(default=0)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("color", models.CharField(blank=True, default="", max_length=10)),
                ("size", models.IntegerField(default=0)),
                ("ball_foot", models.FloatField(default=0)),
                ("instep_foot", models.FloatField(default=0)),
                ("Comfort", models.CharField(blank=True, default="", max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="Shoe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.IntegerField(default=0)),
                (
                    "images",
                    models.ImageField(blank=True, null=True, upload_to="reviews/"),
                ),
                ("description", models.TextField(blank=True)),
                ("source_url", models.TextField()),
                ("weight", models.IntegerField(blank=True, default=0, null=True)),
                ("stock", models.IntegerField(default=0)),
                (
                    "comfort",
                    models.CharField(
                        blank=True,
                        choices=[("VG", "매우좋음"), ("G", "좋음"), ("N", "보통")],
                        default="",
                        max_length=5,
                    ),
                ),
                ("rating", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
