# Generated by Django 5.2.6 on 2025-09-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_order_addr_num_order_detail_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shoe",
            name="image_url",
        ),
        migrations.AddField(
            model_name="brand",
            name="brand_img",
            field=models.ImageField(blank=True, upload_to="brand/"),
        ),
        migrations.AddField(
            model_name="review",
            name="Comfort",
            field=models.CharField(blank=True, default="", max_length=5),
        ),
        migrations.AddField(
            model_name="review",
            name="ball_foot",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="review",
            name="color",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="review",
            name="instep_foot",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="review",
            name="size",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shoe",
            name="comfort",
            field=models.CharField(
                blank=True,
                choices=[("VG", "매우좋음"), ("G", "좋음"), ("N", "보통")],
                default="",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="shoe",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="reviews/"),
        ),
        migrations.AlterField(
            model_name="marathon",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="addr_num",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="detail_address",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="order_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="order",
            name="pay_method",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="shoe",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="shoe",
            name="weight",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name="Registration",
        ),
    ]
